version: "3.6"

networks:
  ycoffee-network:
    driver: bridge

services:
  ycoffee-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ycoffee-api
    restart: always
    command: yarn dev
    ports:
      - "3333:3000"
    volumes:
      - ./backend:/home/node/api
    environment:
      - MONGO_URL=ycoffee-mongo
    depends_on:
      - ycoffee-mongo
    networks:
      - ycoffee-network
    links:
      - ycoffee-mongo

  ycoffee-mongo:
    image: bitnami/mongodb:latest
    container_name: ycoffee-mongo
    restart: always
    env_file: ".env"
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGO_USER}
      - MONGODB_PASSWORD=${MONGO_PASS}
      - MONGODB_DATABASE=${MONGO_DB}
    networks:
      - ycoffee-network
    ports:
      - "27017:27017"
    volumes:
      - ./data/db/mongo:/bitnami
